# Generated by Django 3.1.5 on 2021-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210125_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='main_product/'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
