# Generated by Django 3.1.5 on 2021-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210130_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
