# Generated by Django 3.1.5 on 2021-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210205_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
