# Generated by Django 3.1.5 on 2021-03-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Original_price',
            new_name='original_price',
        ),
    ]
