# Generated by Django 3.1.5 on 2021-02-02 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20210202_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='user_profile',
        ),
    ]
