organisation_category_choices = dict([
    ('PEC', "PEC Faculty/Students"),
    ('OP', 'Other Education Institutes/ CRICK/ R&D'),
    ('I', 'Industry')
])
organisation_choices = {
    "0": "External University/Other Institute/National Lab/Industry",
    "1": " Indian Institute of Technology Patna, Patna  ",
    "2": " NMR Research Centre\r\nIndian Institute of Science, Bangalore  ",
    "3": " Panjab University, Chandigarh  ",
    "4": " Karnatak University, Dharwad, Dharwad  ",
    "5": " Gauhati University, Guwahati  ",
    "6": " Sophisticated Test & Instrumentation Centre, KOCHI  ",
    "7": " Shivaji University, Kolhapur  ",
    "8": " M.G. UniversitySchool of Environmental Sciences, Kottayam  ",
    "9": " Indian Institute of Technology, Bombay, Mumbai  ",
    "10": " All India institute of Medical Sciences (AIIMS) New Delhi,, New Delhi  ",
    "11": " Indian Institute of Engineering Science and Technology, Shibpur, Shibpur  ",
    "12": " North Eastern Hill University, Shillong  ",
    "13": " Charutar Vidya Mandal Vallabh Vidya Nagar, Anand  ",
    "14": " Technology Bhawan, New Delhi  ",
    "15": " New Mehrauli Road,, Chennai  ",
    "16": " CSIR-Central Drug Research Institute,Lucknow, Lucknow  ",
    "17":"Punjab Engineering College, Chandigarh"
}
designation_choices = {
    "0": " AGM (Assistant & Documentation)  ",
    "1": " AGM QAQC  ",
    "2": " Area Convenor  ",
    "3": " Assistant Director  ",
    "4": " ASSISTANT LIBRARIAN  ",
    "5": " Assistant Manager  ",
    "6": " Assistant Professor  ",
    "7": " Associate Professor  ",
    "8": " Associate Professor & Head  ",
    "9": " CANDIDATE  ",
    "10": " Chairman  ",
    "11": " Chairman and HOD  ",
    "12": " CHEMICAL  ",
    "13": " Chemist  ",
    "14": " department of design  ",
    "15": " Deputy General Manager  ",
    "16": " Deputy Manager  ",
    "17": " Deputy Superintending Archaeologist  ",
    "18": " Director  ",
    "19": " Dst Inspire Faculty  ",
    "20": " DST WOS-A  ",
    "21": " Dst Wos- B  ",
    "22": " Emeritus Scientist  ",
    "23": " Executive  ",
    "24": " Extension Lecturer  ",
    "25": " Fellow  ",
    "26": " Head  ",
    "27": " Head, Dept. of Chemistry  ",
    "28": " Head - Project Management  ",
    "29": " Information Scientist  ",
    "30": " IT  ",
    "31": " Joint Director  ",
    "32": " JRF  ",
    "33": " LAB ASSITANT  ",
    "34": " Lab Instructor  ",
    "35": " Lecturer  ",
    "36": " Library Assistant  ",
    "37": " Manager  ",
    "38": " Manager (QA)  ",
    "39": " Manager - Quality  ",
    "40": " M.D.S (final year student)  ",
    "41": " Mphil Scholar  ",
    "42": " M.Phil Scholar  ",
    "43": " Msc  ",
    "44": " M.Sc.  ",
    "45": " National Postdoctoral Fellow  ",
    "46": " National PostDoctoral Fellow  ",
    "47": " Network Engineer  ",
    "48": " OFFICER  ",
    "49": " Officer - Technical  ",
    "50": " owner  ",
    "51": " Partner  ",
    "52": " Pg Student  ",
    "53": " PG Student  ",
    "54": " PhD  ",
    "55": "  Ph.d. Researcher  ",
    "56": "  Phd Researcher  ",
    "57": "  Ph.D. Researcher  ",
    "58": " Ph.d Scholar  ",
    "59": " Phd Scholar  ",
    "60": " PhD Scholar  ",
    "61": " PhD student  ",
    "62": " PhDStudent  ",
    "63": " PhD STUDENT  ",
    "64": " Postdoctoral Fellow  ",
    "65": " Post Doctoral Scientist   ",
    "66": " Principal  ",
    "67": " Principal Analyst  ",
    "68": " Principal Investigatror  ",
    "69": " Principal Researcher  ",
    "70": " Professor  ",
    "71": " Project Assistant  ",
    "72": " Project Fellow  ",
    "73": " Project Student  ",
    "74": " R&d Head  ",
    "75": " Research and Development   ",
    "76": " Research Associate  ",
    "77": " Researcher  ",
    "78": " Research fellow  ",
    "79": " research scholar  ",
    "80": " Research scholar   ",
    "81": " Research Scholar  ",
    "82": " Research Student  ",
    "83": " Research Supervisor  ",
    "84": " Scientific Assistant D  ",
    "85": " Scientific Assistant E  ",
    "86": " Scientific Officer  ",
    "87": " Scientist  ",
    "88": " sdfs  ",
    "89": " Senior Executive Engineer  ",
    "90": " Senior Manager  ",
    "91": " Senior Research Associate  ",
    "92": " Senior Research Fellow  ",
    "93": " Senior Research Scientist  ",
    "94": " SO/E  ",
    "95": " Srf  ",
    "96": " SRF  ",
    "97": " Sr. Scientist  ",
    "98": " Student  ",
    "99": "  Student  ",
    "100": " Teaching Assistant  ",
    "101": " Technical Assistant B  ",
    "102": " Technical Director  ",
    "103": " Technology  ",
    "104": " UGC PDFWM  ",
    "105": " Vice President - Tech.  ",
    "106": " VP Scientific Affairs  ",
    "107": "Other"
}
department_choices = {
    "0": " Accounts & Administration  ",
    "1": " ADL Dept.  ",
    "2": " ADMINISTRATION  ",
    "3": " Advance Construction Management  ",
    "4": " Advanced Capability & Nano Technology  ",
    "5": " Advanced Centre of Research in High Energy Materials  ",
    "6": " Advanced Material and Sensors  ",
    "7": " Aerospace Engineering  ",
    "8": " AESD & CIF  ",
    "9": " Agricultural and Ecological Research Unit  ",
    "10": " Agricultural Chemicals  ",
    "11": " Agrionics  ",
    "12": " Agrionics - Pre Harvest Technologies  ",
    "13": " Agriultural Microbiology  ",
    "14": " aks  ",
    "15": " Alkali Material & Metal Division  ",
    "16": " Analytical Chemistry Laboratory  ",
    "17": " Analytical Development  ",
    "18": " Analytical Research  ",
    "19": " Analytical Research and Development  ",
    "20": " Anatomy  ",
    "21": " Anatomy (EM FACILITY)  ",
    "22": " Animal Science Division, Drdo-defence Institute of High Altitude Research, Leh  ",
    "23": " APD  ",
    "24": " Applied Chemistry  ",
    "25": " Applied Chemistry Department  ",
    "26": " Applied Physics  ",
    "27": " Applied Sciences & Humanities Dept.  ",
    "28": " Archaeological Survey of India  ",
    "29": " Ayurveda Pharmaceutics  ",
    "30": " Barc  ",
    "31": " Basic Sciences and Humanities  ",
    "32": " Bioceramics and Coating  ",
    "33": " Biochemical Engineering  ",
    "34": " Biochemistry  ",
    "35": " Bio-Inorganic and Materials Chemistry Research Laboratory  ",
    "36": " Biological and Environmental Sciences  ",
    "37": " Biological Engineering   ",
    "38": " Biological Sciences Group  ",
    "39": " Biology  ",
    "40": " Bio & Nano Technology  ",
    "41": " Biophysics  ",
    "42": " Biotech  ",
    "43": " Biotechnology  ",
    "44": " Biotechnology and Food Technology  ",
    "45": " Biotechnology & Microbiology  ",
    "46": " Bose Centre  ",
    "47": " Botany  ",
    "48": " BRD School of Biosciences  ",
    "49": " Cancer Biology and Inflammatory Disorder Division  ",
    "50": " Catalysis Division  ",
    "51": " Cdac   ",
    "52": " Center for Green Energy Technology  ",
    "53": " Center for Interdisciplinary Research, D. Y. Patil University, Kolhapur  ",
    "54": " Center for Nanobioscience  ",
    "55": " Center for Research Engineering and Advanced Technology  ",
    "56": " Center For Systems Biology & Bioinformatics  ",
    "57": " Center for VLSI and Nanotechnology  ",
    "58": " Central Research Laboratory  ",
    "59": " Central University  ",
    "60": " Centre For Advanced Energy Studies  ",
    "61": " Centre for biosciences and Biomedical eng.  ",
    "62": " Centre for Biotechnology & Bioinformatics  ",
    "63": " Centre for Energy and Environment  ",
    "64": " Centre for Health safety and Environment  ",
    "65": " Centre For Marine Science and Technology  ",
    "66": " Centre for Nano and Material Sciences  ",
    "67": " Centre for Nano and Materials Sciences  ",
    "68": " Centre for Nano & Material Sciences  ",
    "69": " Centre for Nanosciences  ",
    "70": " Centre for Nano-Sciences & Nanotechnology  ",
    "71": " Centre for Nano-Science & Technology  ",
    "72": " Centre for Ocean Research  ",
    "73": " Centre for Pollution Control & Env. Engg..  ",
    "74": " Centre For Public Health  ",
    "75": " Centre for Rural Development & Technology  ",
    "76": " Centre For Stem Cell and Tissue Engineering  ",
    "77": " Centre for Technology Alternatives for Rural Areas  ",
    "78": " Centre of Materials Science  ",
    "79": " Chemical Engineering  ",
    "80": " Chemical ENgineering  ",
    "81": " Chemical Engineering Department  ",
    "82": " Chemical Engineering Division  ",
    "83": " Chemical Technology Division  ",
    "84": " Chemistry  ",
    "85": " CHEMISTRY  ",
    "86": " Chemistry and Bioprospecting Division  ",
    "87": " Chemistry Division  ",
    "88": " Chemistry, Environment Science, Zoology  ",
    "89": " Civil and Environment Engg. Dept.  ",
    "90": " Civil Engineering  ",
    "91": " Clothing and Textiles Department  ",
    "92": " CNEM  ",
    "93": " Coal  ",
    "94": " COE in Corrosion and Surface Engg  ",
    "95": " COMMERCE  ",
    "96": " Commerce and Management  ",
    "97": " Computational Modelling and Nanoscale Processing Unit  ",
    "98": " Computer Centre  ",
    "99": " Computer Engineering  ",
    "100": " conservaitve and endodontics  ",
    "101": " Coporate Quality Assurance  ",
    "102": " cosmetic technology  ",
    "103": " CRYSTAL GROWTH CENTER  ",
    "104": " Csio  ",
    "105": " csir  ",
    "106": " CSIR-Central Mechanical Engineering Research Institute DURGAPUR  ",
    "107": " Dairy Microbiology Division  ",
    "108": " DBT  ",
    "109": " Deparetment of Petroleum Engineering  ",
    "110": " Department of Agadtantra  ",
    "111": " Department of Agronomy  ",
    "112": " Department Of Applied Chemistry  ",
    "113": " Department of Applied Physics  ",
    "114": " Department of Basic and Applied Science  ",
    "115": " Department of Basic Principles, I.P.G.T. & R.A.  ",
    "116": " Department of Bio and Nanotechnology  ",
    "117": " Department of Bio and Nano Technology  ",
    "118": " Department of Biochemistry  ",
    "119": " Department of  Biochemistry  ",
    "120": " Department Of Biodiversity and Conservation Of Natural Resources  ",
    "121": " Department of Biophysics  ",
    "122": " Department of Biosciences  ",
    "123": " Department of Biotechnology  ",
    "124": " Department of Biotechnology and Bioinformatics  ",
    "125": " Department of Botany  ",
    "126": " Department of Ceramic Engineering  ",
    "127": " Department of Chemical Engineering  ",
    "128": " Department of Chemical Sciences  ",
    "129": " Department of Chemistry  ",
    "130": " Department Of Chemistry  ",
    "131": " Department of Chemistry, Uka Tarsadia University  ",
    "132": " Department of Civil Engg.  ",
    "133": " Department of Conservative Dentistry and Endodontics  ",
    "134": " Department of Dairy Chemistry  ",
    "135": " department of defence  ",
    "136": " Department of Dyestuff Technology  ",
    "137": " Department of Earth Science  ",
    "138": " Department of Electrical Engineering  ",
    "139": " Department of Electronics  ",
    "140": " Department of Electronics and Communication Engineering  ",
    "141": " Department of Engineering Design  ",
    "142": " Department of Entomology  ",
    "143": " Department of Environmental Sciences  ",
    "144": " Department of Environment Studies  ",
    "145": " Department of Fibres and Textile Processing Technology  ",
    "146": " Department of Food and Nutrition  ",
    "147": " Department of Food Engineering & Technology  ",
    "148": " Department of Food Science and Technology  ",
    "149": " Department of Fruit Science  ",
    "150": " Department of Fuel and Mineral Engineering  ",
    "151": " Department of Genetics and Plant Breeding  ",
    "152": " Department of Geology  ",
    "153": " Department of Industrial Chemistry  ",
    "154": " Department of infectious diseases  ",
    "155": " Department of Inorganic Chemistry  ",
    "156": " Department of Life Sciences  ",
    "157": " Department of Livestock Products Technology  ",
    "158": " Department of Marine Science  ",
    "159": " Department of Materials and Metallurgical Engineering  ",
    "160": " Department of Materials and Metallurgy Eng.  ",
    "161": " Department of Materials Science and Nanotechnology  ",
    "162": " DEPARTMENT OF MECHANICAL ENGG.  ",
    "163": " Department of Mechanical Engineering   ",
    "164": " Department of Medicinal Chemistry  ",
    "165": " Department of Microbial Biotechnology  ",
    "166": " Department of Microbiology and Biotechnology Centre  ",
    "167": " Department of Molecular and Cellular Engineering  ",
    "168": " Department of Nano Sciences and Materials  ",
    "169": " Department of Nanotechnology  ",
    "170": " Department of Nuclear Medicine  ",
    "171": " Department of Nuclear Physics  ",
    "172": " Department of Oral & Maxillofacial Pathology  ",
    "173": " Department of Organic Chemistry  ",
    "174": " Department of Paediatric and Preventive Dentistry  ",
    "175": " Department of Pedodontics and Preventive Dentistry  ",
    "176": " Department of periodontology  ",
    "177": " Department of Petroleum Engineering  ",
    "178": " DEPARTMENT OF PHARMACEUTICAL ANALYSIS  ",
    "179": " Department of Pharmaceutical Engineering and Technology  ",
    "180": " Department of Pharmaceutical Sciences  ",
    "181": " Department of Pharmaceutics  ",
    "182": " DEPARTMENT OF PHARMACOGNOSY  ",
    "183": " Department of Pharmacology  ",
    "184": " Department Of Pharmacy  ",
    "185": " Department of Physics  ",
    "186": " Department of Physics & Astrophysics  ",
    "187": " Department of Plant Biology and Plant Biotechnology  ",
    "188": " Department of Plant Pathology  ",
    "189": " DEPARTMENT OF PLANT PATHOLOGY  ",
    "190": " Department of Polymer Engineering  ",
    "191": " Department of Production and Industrial Engineering  ",
    "192": " Department of Prosthodontics  ",
    "193": " Department of prosthodontics and Implantology  ",
    "194": " Department of Pure & Applied Physics  ",
    "195": " Department of School Education  ",
    "196": " Department of Science and Humanities  ",
    "197": " DEPARTMENT OF SOIL SCIENCE AND AGRICULTURAL CHEMISTRY  ",
    "198": " Department of Studies in Biotechnology  ",
    "199": " Department of Studies In Microbiology  ",
    "200": " Department of Technology  ",
    "201": " Department of Veterinary Physiology  ",
    "202": " Department of Zoology  ",
    "203": " Department of Zoonosis  ",
    "204": " Departrment of Chemistry  ",
    "205": " Dept. of Analytical Chemistry  ",
    "206": " Dept of Applied Chemistry  ",
    "207": " Dept. of Applied Geology  ",
    "208": " Dept. of Applied Sciences  ",
    "209": " Dept. Of Biological Sciences  ",
    "210": " Dept. of Biosciences  ",
    "211": " Dept. of Biosciences and Technology  ",
    "212": " Dept. of Biotech. & Genetic Engineering  ",
    "213": " Dept of Biotechnology  ",
    "214": " Dept. of Botany & Env. Science  ",
    "215": " Dept. of Botany & Microbiology  ",
    "216": " Dept. of Chemical, Biological & Macro-Molecular Sciences  ",
    "217": " Dept. of Chemistry  ",
    "218": " Dept. of Civil & Environmental Engineering  ",
    "219": " Dept. of Conservative Dentistry & Endodontics  ",
    "220": " dept of design  ",
    "221": " Dept of ECE  ",
    "222": " Dept. of Electrical & Electronics Engineering  ",
    "223": " Dept. of Electronics & Communication Engg.  ",
    "224": " Dept. Of Electronics & Electrical Communication Engg.  ",
    "225": " Dept. of Energy and Environment  ",
    "226": " Dept. of Energy Technology  ",
    "227": " Dept. of Environmental Engineering  ",
    "228": " Dept. of Environmental Science & Engineering  ",
    "229": " Dept.Of Ethno Medicine and Ethno Pharmacology  ",
    "230": " Dept. of Fibers & Textile Proc. Tech.,  ",
    "231": " Dept. of Food Science and Nutrition  ",
    "232": " Dept. of Instrumentation & USIC  ",
    "233": " Dept. of Marine Science  ",
    "234": " Dept. of Material Science & Mettallurgical Engg.  ",
    "235": " Dept. of Material Science & Mettallurgical Engg.,  ",
    "236": " Dept. of Materials Science & Engineering  ",
    "237": " Dept. of Mechanical and Industrial Engineering  ",
    "238": " Dept. of Mechanical Engineering  ",
    "239": " Dept. of Medical Biotechnology  ",
    "240": " Dept. of Metallurgical and Materials Engineering  ",
    "241": " Dept. of Metallurgical & Materials Engineering  ",
    "242": " Dept. of Metallurgy Engineering and Materials Science  ",
    "243": " Dept. Of Microbiology  ",
    "244": " Dept. Of Microbiology & Biotechnology  ",
    "245": " Dept. of Molecular Biology & Biochemistry  ",
    "246": " Dept. of Molecular Biology & Biotechnology  ",
    "247": " Dept. Of NanoScience and Technology  ",
    "248": " Dept. Of Oils,Oleochemicals & Surfactants Techn.,  ",
    "249": " Dept. of Orthodontics & Dentofacial Orthopaedics  ",
    "250": " Dept. Of Petrochemical Technology  ",
    "251": " Dept of Petroleum Engineering  ",
    "252": " Dept. of Pharmaceutical Analysis  ",
    "253": " Dept. of Pharmaceutical Analysis & Quality Assurance  ",
    "254": " Dept. of Pharmaceutical Biotechnology  ",
    "255": " Dept. of Pharmaceutical Chemistry  ",
    "256": " Dept. of Pharmaceutical Science & Technology  ",
    "257": " Dept. of Pharmaceutical Technology  ",
    "258": " Dept. of Pharmacognosy  ",
    "259": " Dept. of Pharmacognosy and Phytochemistry  ",
    "260": " Dept. of Pharmacology and Toxicology  ",
    "261": " Dept. of Physical Chemistry  ",
    "262": " Dept. of Physics & Electronics  ",
    "263": " Dept. of Physics (Material Science)  ",
    "264": " Dept. Of Physics & Research Centre  ",
    "265": " Dept. of Plant Pathology  ",
    "266": " Dept. of Plastic & Polymer Engg.  ",
    "267": " Dept. of Plastics Technology  ",
    "268": " Dept. of Polymer and Surface Engineering  ",
    "269": " Dept. of Production Engineering  ",
    "270": " Dept. of Prosthodontics  ",
    "271": " Dept. Of Rasashastra  ",
    "272": " Dept. of Rasashastra & Bhaishajyakalpana  ",
    "273": " Dept. of Rasashastra & Bhaishajya Kalpana  ",
    "274": " Dept. of RSBK, AIIA  ",
    "275": " Dept. of Science and Humanities  ",
    "276": " Dept. of Soil Science & Agricultural Chemistry  ",
    "277": " Dept of Textile Technology  ",
    "278": " Dept. of Textile Technology  ",
    "279": " dept. of veterinary pharmacology and toxicology  ",
    "280": " Deptt of Food Science and Technology  ",
    "281": " Division of Biotechnology and Phycology  ",
    "282": " DIVISION OF CLINICAL MEDICINE  ",
    "283": " Division of Infectious   ",
    "284": " Dove Research& Analytics  ",
    "285": " Dr Ssbuicet  ",
    "286": " Dr. Ssbuicet  ",
    "287": " Dyestuff  ",
    "288": " Dyestuff Technology  ",
    "289": " Dyestuff Technology Department  ",
    "290": " Electronics and Instrumentation Engineering  ",
    "291": " Electronics & Telecommunication Dept.  ",
    "292": " Energy Engineering  ",
    "293": " Energy Research Centre, Dept. of Energy Technology  ",
    "294": " Energy Reserach centre panjab university chandigarh  ",
    "295": " Enterprise Service Architecture  ",
    "296": " Environmental Materials Division  ",
    "297": " environment sciences  ",
    "298": " Environment Studies  ",
    "299": " Environment & Sustainability Department  ",
    "300": " Ethnomedicine and Ethnopharmacology  ",
    "301": " Execution of Substations  ",
    "302": " Faculty of Pharmacy  ",
    "303": " Fish Nutrition, Biochemistry & Physiology Division  ",
    "304": " Fish Processing Technology and Engineering Department  ",
    "305": " Food Engg.& Technology Department  ",
    "306": " FOOD ENGINEERING  ",
    "307": " Food Science and Technology  ",
    "308": " Food Science Nutrition and Technology  ",
    "309": " Food Technology Division  ",
    "310": " Forensic Science  ",
    "311": " Forest Products Division  ",
    "312": " Forestry  ",
    "313": " form  ",
    "314": " Formulation  ",
    "315": " for PhD application  ",
    "316": " Fuel Minerals and Metallurgical Engineering  ",
    "317": " Gamete Immunobiology Lab  ",
    "318": " Goa College of Pharmacy  ",
    "319": " Group III/Acc  ",
    "320": " Hemostasis and Thrombosis  ",
    "321": " Humanities and Basic Sciences  ",
    "322": " Human Resources Management  ",
    "323": " Icar  ",
    "324": " I.C Engine Department  ",
    "325": " Ifsc  ",
    "326": " indian design school  ",
    "327": " Industrial & Production Engg. Department  ",
    "328": " Industrial & Production Engineering  ",
    "329": " Industry  ",
    "330": " Institute of Research and Development  ",
    "331": " Institute of Technology  ",
    "332": " Instrumentation Service Division  ",
    "333": " Investigation  ",
    "334": " it  ",
    "335": " IT  ",
    "336": " Khadi and Textile  ",
    "337": " Lawfirm  ",
    "338": " LIBRARY AND INFORMATION CENTRE  ",
    "339": " Manufacturing Division  ",
    "340": " Material Research Centre  ",
    "341": " Material Science and Engineering  ",
    "342": " Materials & Metallurgical Engineering  ",
    "343": " Mechanical Engineering  ",
    "344": " MECHANICAL ENGINEERING  ",
    "345": " Mech Engg Department   ",
    "346": " Medicinal and Aromatic division  ",
    "347": " Metal Finishing  ",
    "348": " Metallurgical Engineering and Material Science  ",
    "349": " Microbiology Department  ",
    "350": " Molecular Biology and Biochemistry  ",
    "351": " molecular biology and genetic engineering  ",
    "352": " MscIT-Experience in Software testing  ",
    "353": " Multidisciplinary Research Unit (MRU)                               ",
    "354": " NA  ",
    "355": " Nanobioscience  ",
    "356": " Nanochemistry Research Lab, Nandurbar  ",
    "357": " Nanochemistry Research Lb, GTP College, Nandurbar  ",
    "358": " Nano Physics and Device Laboratory  ",
    "359": " Nanoscience  ",
    "360": " Nanotechnology  ",
    "361": " Nano Technology Research Centre  ",
    "362": " Nanotherapeutics  ",
    "363": " National Center for Nanosciences & Nanotechnology  ",
    "364": " National Centre for Research & Development  ",
    "365": " Natural Plant Products Division  ",
    "366": " Natural Products  ",
    "367": " Natural products and Green chemistry  ",
    "368": " NEERI  ",
    "369": " Nirrh-dept. of Neuroendocrinology  ",
    "370": " NIRRH, Structural Bilogy Department  ",
    "371": " Nuclear and Atomic Physics  ",
    "372": " Oils, Oleochemicals and Surfactant Technology  ",
    "373": " ONELIFEINDIA  ",
    "374": " Optical Devices & Systems  ",
    "375": " Organic Chemistry Division   ",
    "376": " other  ",
    "377": " Pec  ",
    "378": " Pec Chandigarh  ",
    "379": " petroleum engineering  ",
    "380": " Petroleum Engineering Department  ",
    "381": " P.G. Department of Chemistry  ",
    "382": " P.G. Department of Geology  ",
    "383": " Pg Department of Panchakarma  ",
    "384": " P.G. Dept. of Biosciences  ",
    "385": " P.G. Dept. Of Biotechnology  ",
    "386": " P.G. Dept. of Physics & Electronics  ",
    "387": " P.G. Dept. of Rasashastra & Bhaishajya Kalpana  ",
    "388": " P.G. Pharmaceutics  ",
    "389": " PG & Research Dept. of Biotechnology  ",
    "390": " PG & Research Dept. of Chemistry  ",
    "391": " PG & Research Dept. of Zoology  ",
    "392": " Pharmaceutical Chemistry  ",
    "393": " Pharmaceutical Sciences & Technology Department  ",
    "394": " Pharmaceutics  ",
    "395": " Pharmacognosy & Pharm. Chemistry  ",
    "396": " Pharmacology  ",
    "397": " Physical Sciences Division  ",
    "398": " Physics Department  ",
    "399": " Phytochemistry and Phytopharmacology  ",
    "400": " Planetary Sciences  ",
    "401": " Plant Breeding and Genetics  ",
    "402": " Plant Pathology  ",
    "403": " Polymer and Plastics Technology  ",
    "404": " Polymer Science and Technology  ",
    "405": " Polymers & Functional Materials Division  ",
    "406": " Post Graduate Department of Chemistry  ",
    "407": " Post Harvest Technology  ",
    "408": " Project Management  ",
    "409": " Public Health Dentistry  ",
    "410": " Q.C. Department  ",
    "411": " Quality  ",
    "412": " Quality Assurance Department  ",
    "413": " Quality Control Lab  ",
    "414": " Radioanalytical chemistry Division  ",
    "415": " Radiochemistry Division  ",
    "416": " RADIOCHEMISTRY DIVISION  ",
    "417": " Radiopharmaceuticals Divison  ",
    "418": " Ranauta Currys  ",
    "419": " r and t  ",
    "420": " R & D  ",
    "421": " R&D Centre  ",
    "422": " R &D Division  ",
    "423": " R & D Lab  ",
    "424": " Reaserch and Technology  ",
    "425": " Research Scholar  ",
    "426": " retail  ",
    "427": " SAIF  ",
    "428": " SAIF,IIT Patna  ",
    "429": " SAIF LAB  ",
    "430": " SAIF, NEHU  ",
    "431": " SALES  ",
    "432": " School of Basic & Applied Sciences  ",
    "433": " School of Basic Sciences  ",
    "434": " School of Biochemical Engineering  ",
    "435": " school of biosciences  ",
    "436": " School of Biosciences  ",
    "437": " School of Bio Sciences and Technology  ",
    "438": " School of Biotechnology  ",
    "439": " School of Chemical Sciences  ",
    "440": " School of Chemistry  ",
    "441": " School of Chemistry and Biochemistry  ",
    "442": " School of Earth and Environmental Sciences  ",
    "443": " School of Energy & Environment  ",
    "444": " School of Engineering and Applied Science  ",
    "445": " School of Environmental & Earth Sciences  ",
    "446": " School of Environmental Sciences  ",
    "447": " School of Environmental Studies  ",
    "448": " School of Environment and Sustainable Development  ",
    "449": " School of Life Sciences  ",
    "450": " School of Nano Science and Technology  ",
    "451": " School of Nanoscience & Biotechnology  ",
    "452": " School of NanoSciences  ",
    "453": " School Of Pharmacy  ",
    "454": " School of Physical Sciences  ",
    "455": " School of Physics  ",
    "456": " School Of Physics & Materials Science  ",
    "457": " School of Pure & Applied Physics   ",
    "458": " Science  ",
    "459": " Scientific Information Resource Division  ",
    "460": " SERVICE  ",
    "461": " Service Provider  ",
    "462": " Shcool of Nanoscience and technology  ",
    "463": " Smhs Govt. College  ",
    "464": " Sophisticated Analytical Instrument Facility  ",
    "465": " Stem Cells and Regenerative Medicine   ",
    "466": " Structural Engineering   ",
    "467": " Surface Engineering and Tribology  ",
    "468": " SURFACE ENGINEERING AND TRIBOLOGY DEPARTMENT  ",
    "469": " Technical Services  ",
    "470": " Toxicology  ",
    "471": " Translational Science  ",
    "472": " Ubiquitous Analytical Techniques  ",
    "473": " Uicet  ",
    "474": " Uiet  ",
    "475": " Uiet, Block 2, Applied Sciences,sec-25  ",
    "476": " UM-DAE CEBS  ",
    "477": " University Center of Excellence In Research  ",
    "478": " University Centre of Excellence In Research  ",
    "479": " University Institute of Pharmaceutical Sciences  ",
    "480": " University School of Basic and Applied sciences  ",
    "481": " University School of Chemical Technology  ",
    "482": " Vegetable Scince Division  ",
    "483": " Virology  ",
    "484": " Vivekananda Library  ",
    "485": " Water Treatment Research  ",
    "486": " Yenepoya Research Centre  ",
    "487": " Zoology  ",
    "488": "Other"
}